from listasDobles import DoubleLinkedList
dl = DoubleLinkedList()
dl = DoubleLinkedList()
print(f'¿L está vacía? { dl.is_empty()}')
dl.append(5)
dl.append(7)
dl.append(10)
dl.append(8)
dl.append(12)
dl.append(19)
print(f'¿L está vacía? { dl.is_empty()}')
print(f'Tamaño de la lista: {dl.get_size()}')
dl.transversal()
dl.reverse_transversal()
print(dl.find_from_head(7))
dl.transversal()
print(dl.find_from_tail(0))
dl.remove_from_head(10)
print(f'Tamaño de la lista: {dl.get_size()}')
dl.reverse_transversal()
dl.remove_from_tail(8)
print(f'Tamaño de la lista: {dl.get_size()}')
dl.transversal()
print(f'¿L está vacía? { dl.is_empty()}')
dl.append(1)
dl.append(3)
dl.transversal()
dl.reverse_transversal()
print(dl.find_fromtail(8))
print(dl.find_fromhead(1))
print(dl.find_fromtail(1))
print(dl.find_fromhead(8))
